
rocketmq:
  name-server: 192.168.213.132:9876

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/charity?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    continue-on-error: false

  devtools:
    restart:
      enabled: true

  jpa:
    properties:
      hibernate.hbm2ddl.auto: update
    show-sql: true

  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: GMT+8

