version: "3"
services:
  db:
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=charity"
    ports:
      - "3306:3306"
    volumes:
      - "./database/.data:/var/lib/mysql"
      - "./database/sql:/docker-entrypoint-initdb.d/"

  redis:
    image: redis
    ports:
    - "6379:6379"

#  elasticsearch:
#    image: elasticsearch:6.4.3
#    environment:
#      - "discovery.type=single-node"
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    volumes:
#      - "./elasticsearch/.data:/usr/share/elasticsearch/data"

#  kibana:
#    image: kibana:6.4.3
#    ports:
#      - "5601:5601"

#  namesrv:
#    image: rocketmqinc/rocketmq
#    ports:
#      - 9876:9876
#    environment:
#      JAVA_HOME: /usr/lib/jvm/jre
#      JAVA_OPT_EXT: "-Xms1g -Xmx1g -Xmn512m"
#    command: sh mqnamesrv
#
#  broker:
#    image: rocketmqinc/rocketmq
#    ports:
#      - 10909:10909
#      - 10911:10911
#      - 10912:10912
#    volumes:
#      - ./rocketmq/conf/broker.conf:/etc/rocketmq/conf/broker.conf
#      - ./rocketmq/.data:/root
#    #command: sh mqbroker -n namesrv:9876
#    command: sh mqbroker -n namesrv:9876 -c /etc/rocketmq/conf/broker.conf
#    depends_on:
#      - namesrv
#    environment:
#      JAVA_HOME: /usr/lib/jvm/jre
#      JAVA_OPT_EXT: "-Xms1g -Xmx1g -Xmn512m"
#
#  console:
#    image: styletang/rocketmq-console-ng
#    ports:
#      - 8087:8080
#    depends_on:
#      - namesrv
#    environment:
#      - JAVA_OPTS= -Dlogging.level.root=info   -Drocketmq.namesrv.addr=namesrv:9876
#      - Dcom.rocketmq.sendMessageWithVIPChannel=false

